experiment_name: 'test'
data_path: 'data/orig_data/human_reduced_results.csv'
folder_path: 'data/orig_data/input_data/reduced_clean/'
results_path: 'data/orig_data/graph_results/res_'
graph_path: 'data/orig_data/graphs/'
graph_types:
  del:
#  mst:
#  knn: [1]
#  kncg: [2]
#  gong: [0.35]
#  rng:
#  bt: [0.005, 0.02, 0.05]
#  as: [0.01]
#  cbsg: [0.2]
purities:
  type: ['ltcc', 'cp', 'ce', 'mv', 'mcec']
  pessimism: [True, False]
  class: 1


