experiment_name: 'test_1'
data_path: 'data/orig_data/human_reduced_results.csv'
folder_path: 'data/orig_data/input_data/enhanced_dim_data/'
results_path: 'data/orig_data/graph_results/res_'
dict_path: 'data/orig_data/graph_results/res_dict_'
graph_path: 'data/orig_data/graphs/'
graph_types:
  del:
  knn: [2, 4, 5]
#  cbsg: [2]
purities:
  type: ['ltcc', 'cp', 'ce', 'mv', 'mcec']


