experiment_name: 'graph_neighbourhoods_1'
data_path: 'data/RESULTS_EUROVIS2015.csv'
results_path: 'data/results/res_'
folder_path: "data/EUROVIS_new/"
graph_path: 'data/graphs/'
graph_types:
  del:
  mst:
  knn: [1]
#  kncg: [2]
#  gong: [0.35]
#  rng:
#  bt: [0.005, 0.02, 0.05]
#  as: [0.01]
#  cbsg: [0.2]
purities:
  type: ['mcec', 'ltcc', 'cp', 'ce', 'mv']
  pessimism: [True, False]
  class: 1


