experiment_name: 'kncg_gong'
data_path: 'data/RESULTS_EUROVIS2015.csv'
results_path: 'data/results/res_'
folder_path: "data/EUROVIS_new/"
graph_path: 'data/graphs/'
graph_types:
#  del:
#  mst:
#  knn: [1,2,3,4,6,8,10,12]
  kncg: [2,4,6]
  gong: [0.5, 0.1, 0.35]
#  rng:
#  bt: [0.005, 0.02, 0.05, 0.1, 0.2, 0.5]
#  as: [0.01, 0.02, 0.05, 0.1, 0.45, 0.5]
#  cbsg: [0.2]
purities:
  type: ['mcec', 'ltcc', 'cp', 'ce', 'mv']
  pessimism: [True, False]
  class: 1
