experiment_name: 'mturk_batch'
folder_path: 'data/mturk_samples/phase1/data/'
results_path: 'data/mturk_samples/phase1/graph_results/res_'
dict_path: 'data/mturk_samples/phase1/graph_results/res_dict_'
graph_path: 'data/mturk_samples/phase1/graphs/'
graph_types:
  knn: [1, 2, 4, 6, 8]
  del:
  bt: [0.02, 0.05, 0.1, 0.5]
  as: [0.02, 0.05, 0.1, 0.5]
  cbsg: [0.1, 0.2, 0.5, 2]
purities:
  type: ['ltcc', 'cp', 'ce', 'mv', 'mcec']


